language: android
script: ./gradlew check --continue
android:
  components:
    # The BuildTools version used by your project, must match the values in app/build.gradle
    - build-tools-23.0.3

    # The SDK version used to compile your project, must match the values in app/build.gradle
    - android-23

    # For appcompat-v7 support library
    - extra-android-m2repository

    # From: https://docs.travis-ci.com/user/languages/android#Overview
    # Use the latest revision of Android SDK Tools
    - platform-tools
    - tools
